
#Comportamiento del servidor web Nginx
#Puerto, página principal
#Carpeta raiz
#Acción ante errores, peticiones y bloqueo de acceso
server {
    listen 80;
    index index.php index.html;
    #Carpeta raiz
    root /var/www/src/public;

    #Intenta servir el archivo, si no existe 
    #lo manda a index.php (asé funciona laravel)
    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    #Pasa la petición php al contenedor app:9000
    location ~ \.php$ {
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $realpath_root$fastcgi_script_name;
        include fastcgi_params;
    }
    #bloque el acceso a archivos ocultos como .env
    location ~ /\.(?!well-known).* {
        deny all;
    }
}